apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovpn0
  labels:
    app: ovpn0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ovpn0
  template:
    metadata:
      labels:
        app: ovpn0
    spec:
      containers:
      - image: linuxserver/openvpn-as
        name: ovpn
        env:
          - name: PUID
            value: 1000
          - name: PGID
            value: 1000
          - name: TZ
            value: Europe/London
        ports:
        - containerPort: 943
          name: por1
        - containerPort: 9443
          name: por2
        - containerPort: 1194
          name: openvpn
          protocol: UDP
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
